/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package internalpage;

/**
 *
 * @author User
 */
import CONFIG.DBCONNECTOR;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import net.proteanit.sql.DbUtils;
public class addbook extends javax.swing.JInternalFrame {

    /** Creates new form addbook */
    public addbook() {
        initComponents();
        displayData();
          this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        BasicInternalFrameUI bi = (BasicInternalFrameUI) this.getUI();
        bi.setNorthPane(null);
    }
      public void reset(){
   EN.setText("");
   EBT.setText("");
   EG.setText("");
   ED.setText("");
   QUANT.setText("");
   }
    
    
    public void displayData(){
        try{
       
            DBCONNECTOR dbc = new DBCONNECTOR();
            ResultSet rs = dbc.getData("SELECT * FROM book_details");
            BOOKDET.setModel(DbUtils.resultSetToTableModel(rs));
       
        }catch(SQLException ex){
            System.out.println("Error Message: "+ex);
       
        }
    
     }
    public void filltable () throws SQLException{
        try{
            DBCONNECTOR dbc = new DBCONNECTOR();
            ResultSet rs = dbc.getData("SELECT * FROM book_details");
            BOOKDET.setModel(DbUtils.resultSetToTableModel(rs));
        }catch(SQLException ex){
        
        }
    
    }
      public boolean validation(){
  String isbn= EN.getText();
String tittle =  EBT.getText();
  String genre = EG.getText();
String ed= ED.getText();
String qauntity= QUANT.getText();
 if (isbn.equals("")){
 JOptionPane.showMessageDialog(this, "PLEASE ENTER ISBN");
 return false;
 }
 if(tittle.equals("")){
 JOptionPane.showMessageDialog(this, "PLEASE ENTER TITTLE");
 return false;
 }
if(genre.equals("")){
 JOptionPane.showMessageDialog(this, "PLEASE ENTER GENRE");
 return false;
 }     
 if(ed.equals("")){
 JOptionPane.showMessageDialog(this, "PLEASE ENTER EDITION");
 return false;
 }    
  if(qauntity.equals("")){
 JOptionPane.showMessageDialog(this, "PLEASE ENTER QUANTITY");
 return false;
 }        
 
   return true;  
 }
   

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        EN = new javax.swing.JTextField();
        EBT = new javax.swing.JTextField();
        EG = new javax.swing.JTextField();
        ED = new javax.swing.JTextField();
        ADD = new javax.swing.JButton();
        UPDATE = new javax.swing.JButton();
        DELETE = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        QUANT = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        BOOKDET = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(227, 167, 114));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        EN.setBackground(new java.awt.Color(241, 195, 4));
        EN.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        EN.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        EN.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2), "ENTER ISBN", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Yu Gothic UI", 1, 12))); // NOI18N
        jPanel1.add(EN, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, 210, 40));

        EBT.setBackground(new java.awt.Color(241, 195, 4));
        EBT.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        EBT.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        EBT.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2), "ENTER BOOK TITTLE", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Yu Gothic UI", 1, 12))); // NOI18N
        EBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EBTActionPerformed(evt);
            }
        });
        jPanel1.add(EBT, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, 210, 40));

        EG.setBackground(new java.awt.Color(241, 195, 4));
        EG.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        EG.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        EG.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2), "ENTER GENRE", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Yu Gothic UI", 1, 12))); // NOI18N
        jPanel1.add(EG, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, 210, 40));

        ED.setBackground(new java.awt.Color(241, 195, 4));
        ED.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        ED.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ED.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2), "ENTER EDITION", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Yu Gothic UI", 1, 12))); // NOI18N
        ED.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                EDKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                EDKeyTyped(evt);
            }
        });
        jPanel1.add(ED, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, 210, 40));

        ADD.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        ADD.setText("ADD");
        ADD.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        ADD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ADDActionPerformed(evt);
            }
        });
        jPanel1.add(ADD, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 430, 80, 30));

        UPDATE.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        UPDATE.setText("UPDATE");
        UPDATE.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        UPDATE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UPDATEActionPerformed(evt);
            }
        });
        jPanel1.add(UPDATE, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 430, 80, 30));

        DELETE.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        DELETE.setText("DELETE");
        DELETE.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        DELETE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DELETEActionPerformed(evt);
            }
        });
        jPanel1.add(DELETE, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 430, 80, 30));

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("ADD BOOK");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 280, 40));

        QUANT.setBackground(new java.awt.Color(241, 195, 4));
        QUANT.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        QUANT.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        QUANT.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2), "ENTER QUANTITY", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Yu Gothic UI", 1, 12))); // NOI18N
        QUANT.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                QUANTKeyTyped(evt);
            }
        });
        jPanel1.add(QUANT, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 350, 210, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 310, 520));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BOOKDET.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BOOKDETMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(BOOKDET);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 560, 520));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/library-books-laptop-table-wallpaper-preview.jpg"))); // NOI18N
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 810, 510));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(305, 0, 540, 490));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EBTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EBTActionPerformed

    private void ADDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ADDActionPerformed
     if(validation()== true){
        
        DBCONNECTOR dbc = new DBCONNECTOR();
        dbc.insertData("INSERT INTO book_details ( ISBN, TITTLE, GENRE, EDITION, QUANTITY) "
                + "VALUES ('"+EN.getText()+"','"+EBT.getText()+"','"+EG.getText()+"','"+ED.getText()+"','"+QUANT.getText()+"')");
        displayData();
        reset();
     }              
    }//GEN-LAST:event_ADDActionPerformed

    private void UPDATEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UPDATEActionPerformed
       if(validation()== true){
        DBCONNECTOR dbc = new DBCONNECTOR();
        int num = dbc.updateData("UPDATE book_details SET TITTLE "
                + "= '"+EBT.getText()+"', GENRE = '"+EG.getText()+"', EDITION "
                        + "= '"+ED.getText()+"', QUANTITY = '"+QUANT.getText()+"' WHERE ISBN = '"+EN.getText()+"'");
        if(num ==0){
        
        }else{
        JOptionPane.showMessageDialog(null, "updated successfully");
        displayData();
        reset();
        }
       }  
    }//GEN-LAST:event_UPDATEActionPerformed

    private void DELETEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DELETEActionPerformed
       int rowIndex = BOOKDET.getSelectedRow();
       if(rowIndex < 0){
           JOptionPane.showMessageDialog(null, "Please select a data first");
       }else{
            TableModel model = BOOKDET.getModel();
            Object value = model.getValueAt(rowIndex, 0);
            String ISBN = value.toString();
             int a=JOptionPane.showConfirmDialog(null,"Are you sure?");  
                    if(a==JOptionPane.YES_OPTION){  
                            DBCONNECTOR dbc = new DBCONNECTOR();
                            dbc.deleteData1(Integer.parseInt(ISBN));
                            displayData();
                            reset();
                    }    
       }
    }//GEN-LAST:event_DELETEActionPerformed

    private void BOOKDETMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BOOKDETMouseClicked
      int rowIndex = BOOKDET.getSelectedRow();
        if(rowIndex <0){
        
        }else{
        TableModel model = BOOKDET.getModel();

        EN.setText(""+model.getValueAt(rowIndex, 0));
        EBT.setText(""+model.getValueAt(rowIndex, 1));
        EG.setText(""+model.getValueAt(rowIndex, 2));
        ED.setText(""+model.getValueAt(rowIndex, 3));
        QUANT.setText(""+model.getValueAt(rowIndex, 4));
        }
    }//GEN-LAST:event_BOOKDETMouseClicked

    private void EDKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_EDKeyPressed
        char c =evt.getKeyChar();
        if(Character.isLetter(c)){
        ED.setEditable(false);
        JOptionPane.showMessageDialog(this, "Please enter number only");
        }else{
        ED.setEditable(true);
        
        }
    }//GEN-LAST:event_EDKeyPressed

    private void EDKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_EDKeyTyped
    
    }//GEN-LAST:event_EDKeyTyped

    private void QUANTKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_QUANTKeyTyped
       char c =evt.getKeyChar();
        if(Character.isLetter(c)){
        QUANT.setEditable(false);
        JOptionPane.showMessageDialog(this, "PLease enter number only");
        }else{
       QUANT.setEditable(true);
        
        }
    }//GEN-LAST:event_QUANTKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ADD;
    private javax.swing.JTable BOOKDET;
    private javax.swing.JButton DELETE;
    private javax.swing.JTextField EBT;
    private javax.swing.JTextField ED;
    private javax.swing.JTextField EG;
    private javax.swing.JTextField EN;
    private javax.swing.JTextField QUANT;
    private javax.swing.JButton UPDATE;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

}
