/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package internalpage;

import com.mysql.cj.jdbc.PreparedStatementWrapper;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import java.sql.*;
import javax.swing.JOptionPane;
/**
 *
 * @author User
 */public class returnbook extends javax.swing.JInternalFrame {
  private Connection connection;
    /**
     * Creates new form returnbook
     */
    public returnbook() {
        initComponents();
          this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        BasicInternalFrameUI bi = (BasicInternalFrameUI) this.getUI();
        bi.setNorthPane(null);
        
    }
public void issuedbookdetails(){
  
 int bookid = Integer.parseInt(ISBN.getText());
 int sid= Integer.parseInt(STUDid.getText());
 
    try {
         connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/library_ba", "root", "");
         String sql = "SELECT * FROM issue_book_details where ISBN = ? and ID = ? and STATUS =?";
        PreparedStatement pst = connection.prepareStatement(sql);
        
        pst.setInt(1, bookid);
        pst.setInt(2, sid);
        pst.setString(3, "PENDING");
        
        ResultSet rs = pst.executeQuery();
        if(rs.next()){
            
        ISSUEDID.setText(rs.getString("ISSUED_ID"));
        TITLE.setText(rs.getString("ISBN"));
        STUDNAME.setText(rs.getString("NAME"));
        ISSUEDDATE.setText(rs.getString("ISSUED"));
        DUEDATE.setText(rs.getString("DUE"));
        ERROR.setText(rs.getString(""));
        }else{
            
        ERROR.setText("NO RECORD FOUND");
          ISSUEDID.setText(" ");
        TITLE.setText(" ");
        STUDNAME.setText(" ");
        ISSUEDDATE.setText(" ");
        DUEDATE.setText("  ");
        }
    } catch (Exception e) {
        e.printStackTrace();
    }
}

public boolean returnbook(){
boolean isreturnbook = false;
 int bookid = Integer.parseInt(ISBN.getText());
 int sid= Integer.parseInt(STUDid.getText());
    try {
        connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/library_ba", "root", "");
         String sql = "update issue_book_details set STATUS = ? where ID = ? and ISBN = ? and STATUS = ?";
         PreparedStatement pst = connection.prepareStatement(sql);
         pst.setString(1, "RETURNED");
        pst.setInt(2, sid);
        pst.setInt(3, bookid);
        pst.setString(4, "PENDING");
        
        int rowcount = pst.executeUpdate();
        if(rowcount>0){
            isreturnbook = true;
        }else{
            isreturnbook = false;
        
        }
    } catch (Exception e) {
        e.printStackTrace();
    }
    return isreturnbook;
}
public void updatebookquant(){
 int bookid= Integer.parseInt(ISBN.getText());
     try {
          connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/library_ba", "root", "");
          String sql = "update book_details set QUANTITY = QUANTITY + 1 where ISBN =?";
          PreparedStatement pst = connection.prepareStatement(sql);
          pst.setInt(1, bookid);
          
        int rowcount = pst.executeUpdate();
          
          if(rowcount>0){
          JOptionPane.showMessageDialog(this, "BOOK QUANTITY UPDATED");
        
          }else{
          JOptionPane.showMessageDialog(this, "BOOK QUANTITY FAILED TO UPDATED");
          }
     } catch (Exception e) {
         e.printStackTrace();
     }
 }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        ISSUEDID = new javax.swing.JLabel();
        TITLE = new javax.swing.JLabel();
        STUDNAME = new javax.swing.JLabel();
        ISSUEDDATE = new javax.swing.JLabel();
        DUEDATE = new javax.swing.JLabel();
        ERROR = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        ISBN = new javax.swing.JTextField();
        STUDid = new javax.swing.JTextField();
        FINDET = new javax.swing.JButton();
        RETURNBOOK = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();

        setBackground(new java.awt.Color(153, 102, 0));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(153, 51, 0));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 153));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("ISSUED BOOK DETAILS");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, 240, 50));

        ISSUEDID.setBackground(new java.awt.Color(204, 204, 204));
        ISSUEDID.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        ISSUEDID.setForeground(new java.awt.Color(0, 255, 0));
        ISSUEDID.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ISSUEDID.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2), "ISSUED ID", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Yu Gothic UI", 1, 14), new java.awt.Color(0, 0, 255))); // NOI18N
        jPanel2.add(ISSUEDID, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, 230, 50));

        TITLE.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        TITLE.setForeground(new java.awt.Color(0, 255, 0));
        TITLE.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TITLE.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2), "TITLE", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Yu Gothic UI", 1, 14), new java.awt.Color(0, 0, 204))); // NOI18N
        jPanel2.add(TITLE, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, 230, 50));

        STUDNAME.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        STUDNAME.setForeground(new java.awt.Color(0, 255, 0));
        STUDNAME.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        STUDNAME.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2), "NAME", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Yu Gothic UI", 1, 14), new java.awt.Color(0, 0, 204))); // NOI18N
        jPanel2.add(STUDNAME, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 230, 230, 50));

        ISSUEDDATE.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        ISSUEDDATE.setForeground(new java.awt.Color(0, 255, 0));
        ISSUEDDATE.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ISSUEDDATE.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2), "ISSUED DATE", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Yu Gothic UI", 1, 14), new java.awt.Color(0, 0, 204))); // NOI18N
        jPanel2.add(ISSUEDDATE, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 300, 230, 50));

        DUEDATE.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        DUEDATE.setForeground(new java.awt.Color(0, 255, 0));
        DUEDATE.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        DUEDATE.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2), "DUE DATE", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Yu Gothic UI", 1, 14), new java.awt.Color(0, 0, 204))); // NOI18N
        jPanel2.add(DUEDATE, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 360, 230, 50));

        ERROR.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        ERROR.setForeground(new java.awt.Color(153, 255, 204));
        jPanel2.add(ERROR, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 424, 370, 40));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 410, 490));

        jPanel3.setBackground(new java.awt.Color(153, 102, 0));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 153));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("RETURN BOOK");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, 240, 50));

        ISBN.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "ISBN", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Yu Gothic UI", 1, 14))); // NOI18N
        ISBN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ISBNActionPerformed(evt);
            }
        });
        jPanel3.add(ISBN, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, 270, 40));

        STUDid.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "STUDENT ID", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Yu Gothic UI", 1, 14))); // NOI18N
        STUDid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                STUDidActionPerformed(evt);
            }
        });
        jPanel3.add(STUDid, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 230, 270, 40));

        FINDET.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        FINDET.setText("FIND DETAILS");
        FINDET.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FINDETActionPerformed(evt);
            }
        });
        jPanel3.add(FINDET, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 320, 250, 30));

        RETURNBOOK.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        RETURNBOOK.setText("RETURN BOOK");
        RETURNBOOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RETURNBOOKActionPerformed(evt);
            }
        });
        jPanel3.add(RETURNBOOK, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 370, 250, 30));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 0, 470, 490));
        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 0, 50, 490));

        jPanel5.setBackground(new java.awt.Color(153, 51, 0));

        jPanel6.setBackground(new java.awt.Color(153, 102, 0));

        jPanel8.setBackground(new java.awt.Color(153, 102, 0));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 840, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createSequentialGroup()
                .addGap(808, 808, 808)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(410, 410, 410)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 570, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createSequentialGroup()
                .addGap(455, 455, 455)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ISBNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ISBNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ISBNActionPerformed

    private void STUDidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_STUDidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_STUDidActionPerformed

    private void FINDETActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FINDETActionPerformed
      issuedbookdetails();
    }//GEN-LAST:event_FINDETActionPerformed

    private void RETURNBOOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RETURNBOOKActionPerformed
       if(returnbook()== true){
       JOptionPane.showMessageDialog(this, "BOOK RETURNED SUCCESSFULLY");
       updatebookquant();   
       }else{
       JOptionPane.showMessageDialog(this, "BOOK RETURNED FAILED ");
       }
    }//GEN-LAST:event_RETURNBOOKActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel DUEDATE;
    private javax.swing.JLabel ERROR;
    private javax.swing.JButton FINDET;
    private javax.swing.JTextField ISBN;
    private javax.swing.JLabel ISSUEDDATE;
    private javax.swing.JLabel ISSUEDID;
    private javax.swing.JButton RETURNBOOK;
    private javax.swing.JLabel STUDNAME;
    private javax.swing.JTextField STUDid;
    private javax.swing.JLabel TITLE;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    // End of variables declaration//GEN-END:variables
}
